### ISSUE TITLE
Feltöltve

### ISSUE THREAD

**Issue by ui3exn** [Teaching-projects/SZE-FordProg-2020-Liquid#1]
Feltöltöttem a beadandót, valamint egy rövid README-t.

**Comment by hegyhati** [comment]
Ez igy mar nagyjabol rendben van/lenne. Az erzesem az, hogy ez a nyelvtan egy csomo minden mast is general, amit nem kellene. Legalabbis eleg kaotikusan osszerakottnak tunnek a szabalyok. . Illetve ugy tunik, hogy a `p[0]` szerepe nem teljesen tiszta.  Beirok egy elegsegest.
